CREATE TABLE antibiotics_count as
with di as
(
select
  di.*
from d_items di
where
(
     lower(label) like '%' || lower('adoxa') || '%'
  or lower(label) like '%' || lower('ala-tet') || '%'
  or lower(label) like '%' || lower('alodox') || '%'
  or lower(label) like '%' || lower('amikacin') || '%'
  or lower(label) like '%' || lower('amikin') || '%'
  or lower(label) like '%' || lower('amoxicillin') || '%'
  or lower(label) like '%' || lower('amoxicillin%clavulanate') || '%'
  or lower(label) like '%' || lower('clavulanate') || '%'
  or lower(label) like '%' || lower('ampicillin') || '%'
  or lower(label) like '%' || lower('augmentin') || '%'
  or lower(label) like '%' || lower('avelox') || '%'
  or lower(label) like '%' || lower('avidoxy') || '%'
  or lower(label) like '%' || lower('azactam') || '%'
  or lower(label) like '%' || lower('azithromycin') || '%'
  or lower(label) like '%' || lower('aztreonam') || '%'
  or lower(label) like '%' || lower('axetil') || '%'
  or lower(label) like '%' || lower('bactocill') || '%'
  or lower(label) like '%' || lower('bactrim') || '%'
  or lower(label) like '%' || lower('bethkis') || '%'
  or lower(label) like '%' || lower('biaxin') || '%'
  or lower(label) like '%' || lower('bicillin l-a') || '%'
  or lower(label) like '%' || lower('cayston') || '%'
  or lower(label) like '%' || lower('cefazolin') || '%'
  or lower(label) like '%' || lower('cedax') || '%'
  or lower(label) like '%' || lower('cefoxitin') || '%'
  or lower(label) like '%' || lower('ceftazidime') || '%'
  or lower(label) like '%' || lower('cefaclor') || '%'
  or lower(label) like '%' || lower('cefadroxil') || '%'
  or lower(label) like '%' || lower('cefdinir') || '%'
  or lower(label) like '%' || lower('cefditoren') || '%'
  or lower(label) like '%' || lower('cefepime') || '%'
  or lower(label) like '%' || lower('cefotetan') || '%'
  or lower(label) like '%' || lower('cefotaxime') || '%'
  or lower(label) like '%' || lower('cefpodoxime') || '%'
  or lower(label) like '%' || lower('cefprozil') || '%'
  or lower(label) like '%' || lower('ceftibuten') || '%'
  or lower(label) like '%' || lower('ceftin') || '%'
  or lower(label) like '%' || lower('cefuroxime ') || '%'
  or lower(label) like '%' || lower('cefuroxime') || '%'
  or lower(label) like '%' || lower('cephalexin') || '%'
  or lower(label) like '%' || lower('chloramphenicol') || '%'
  or lower(label) like '%' || lower('cipro') || '%'
  or lower(label) like '%' || lower('ciprofloxacin') || '%'
  or lower(label) like '%' || lower('claforan') || '%'
  or lower(label) like '%' || lower('clarithromycin') || '%'
  or lower(label) like '%' || lower('cleocin') || '%'
  or lower(label) like '%' || lower('clindamycin') || '%'
  or lower(label) like '%' || lower('cubicin') || '%'
  or lower(label) like '%' || lower('dicloxacillin') || '%'
  or lower(label) like '%' || lower('doryx') || '%'
  or lower(label) like '%' || lower('doxycycline') || '%'
  or lower(label) like '%' || lower('duricef') || '%'
  or lower(label) like '%' || lower('dynacin') || '%'
  or lower(label) like '%' || lower('ery-tab') || '%'
  or lower(label) like '%' || lower('eryped') || '%'
  or lower(label) like '%' || lower('eryc') || '%'
  or lower(label) like '%' || lower('erythrocin') || '%'
  or lower(label) like '%' || lower('erythromycin') || '%'
  or lower(label) like '%' || lower('factive') || '%'
  or lower(label) like '%' || lower('flagyl') || '%'
  or lower(label) like '%' || lower('fortaz') || '%'
  or lower(label) like '%' || lower('furadantin') || '%'
  or lower(label) like '%' || lower('garamycin') || '%'
  or lower(label) like '%' || lower('gentamicin') || '%'
  or lower(label) like '%' || lower('kanamycin') || '%'
  or lower(label) like '%' || lower('keflex') || '%'
  or lower(label) like '%' || lower('ketek') || '%'
  or lower(label) like '%' || lower('levaquin') || '%'
  or lower(label) like '%' || lower('levofloxacin') || '%'
  or lower(label) like '%' || lower('lincocin') || '%'
  or lower(label) like '%' || lower('macrobid') || '%'
  or lower(label) like '%' || lower('macrodantin') || '%'
  or lower(label) like '%' || lower('maxipime') || '%'
  or lower(label) like '%' || lower('mefoxin') || '%'
  or lower(label) like '%' || lower('metronidazole') || '%'
  or lower(label) like '%' || lower('minocin') || '%'
  or lower(label) like '%' || lower('minocycline') || '%'
  or lower(label) like '%' || lower('monodox') || '%'
  or lower(label) like '%' || lower('monurol') || '%'
  or lower(label) like '%' || lower('morgidox') || '%'
  or lower(label) like '%' || lower('moxatag') || '%'
  or lower(label) like '%' || lower('moxifloxacin') || '%'
  or lower(label) like '%' || lower('myrac') || '%'
  or lower(label) like '%' || lower('nafcillin sodium') || '%'
  or lower(label) like '%' || lower('nicazel doxy 30') || '%'
  or lower(label) like '%' || lower('nitrofurantoin') || '%'
  or lower(label) like '%' || lower('noroxin') || '%'
  or lower(label) like '%' || lower('ocudox') || '%'
  or lower(label) like '%' || lower('ofloxacin') || '%'
  or lower(label) like '%' || lower('omnicef') || '%'
  or lower(label) like '%' || lower('oracea') || '%'
  or lower(label) like '%' || lower('oraxyl') || '%'
  or lower(label) like '%' || lower('oxacillin') || '%'
  or lower(label) like '%' || lower('pc pen vk') || '%'
  or lower(label) like '%' || lower('pce dispertab') || '%'
  or lower(label) like '%' || lower('panixine') || '%'
  or lower(label) like '%' || lower('pediazole') || '%'
  or lower(label) like '%' || lower('penicillin') || '%'
  or lower(label) like '%' || lower('periostat') || '%'
  or lower(label) like '%' || lower('pfizerpen') || '%'
  or lower(label) like '%' || lower('piperacillin') || '%'
  or lower(label) like '%' || lower('tazobactam') || '%'
  or lower(label) like '%' || lower('primsol') || '%'
  or lower(label) like '%' || lower('proquin') || '%'
  or lower(label) like '%' || lower('raniclor') || '%'
  or lower(label) like '%' || lower('rifadin') || '%'
  or lower(label) like '%' || lower('rifampin') || '%'
  or lower(label) like '%' || lower('rocephin') || '%'
  or lower(label) like '%' || lower('smz-tmp') || '%'
  or lower(label) like '%' || lower('septra') || '%'
  or lower(label) like '%' || lower('septra ds') || '%'
  or lower(label) like '%' || lower('septra') || '%'
  or lower(label) like '%' || lower('solodyn') || '%'
  or lower(label) like '%' || lower('spectracef') || '%'
  or lower(label) like '%' || lower('streptomycin sulfate') || '%'
  or lower(label) like '%' || lower('sulfadiazine') || '%'
  or lower(label) like '%' || lower('sulfamethoxazole') || '%'
  or lower(label) like '%' || lower('trimethoprim') || '%'
  or lower(label) like '%' || lower('sulfatrim') || '%'
  or lower(label) like '%' || lower('sulfisoxazole') || '%'
  or lower(label) like '%' || lower('suprax') || '%'
  or lower(label) like '%' || lower('synercid') || '%'
  or lower(label) like '%' || lower('tazicef') || '%'
  or lower(label) like '%' || lower('tetracycline') || '%'
  or lower(label) like '%' || lower('timentin') || '%'
  or lower(label) like '%' || lower('tobi') || '%'
  or lower(label) like '%' || lower('tobramycin') || '%'
  or lower(label) like '%' || lower('trimethoprim') || '%'
  or lower(label) like '%' || lower('unasyn') || '%'
  or lower(label) like '%' || lower('vancocin') || '%'
  or lower(label) like '%' || lower('vancomycin') || '%'
  or lower(label) like '%' || lower('vantin') || '%'
  or lower(label) like '%' || lower('vibativ') || '%'
  or lower(label) like '%' || lower('vibra-tabs') || '%'
  or lower(label) like '%' || lower('vibramycin') || '%'
  or lower(label) like '%' || lower('zinacef') || '%'
  or lower(label) like '%' || lower('zithromax') || '%'
  or lower(label) like '%' || lower('zmax') || '%'
  or lower(label) like '%' || lower('zosyn') || '%'
  or lower(label) like '%' || lower('zyvox') || '%'
)
)
select di.itemid, di.label, di.linksto
  , (count(ce.itemid) + count(cv.itemid) + count(mv.itemid) + count(me.ab_itemid)) as NumObs
  , (count(distinct ce.hadm_id) + count(distinct cv.hadm_id) + count(distinct mv.hadm_id) + count(distinct me.hadm_id)) as NumPat
from di
left join chartevents ce
  on di.itemid = ce.itemid
  and di.linksto = 'chartevents'
left join inputevents_mv mv
  on di.itemid = mv.itemid
  and di.linksto = 'inputevents_mv'
left join inputevents_cv cv
  on di.itemid = cv.itemid
  and di.linksto = 'inputevents_cv'
left join microbiologyevents me
  on di.itemid = me.ab_itemid
  and di.linksto = 'microbiologyevents'
group by di.itemid, di.label, di.linksto;
